const wastesType = [
{name:"Sitoktoksik", description: "Limbah sitotoksik adalah jenis limbah yang mengandung bahan kimia atau zat-zat yang memiliki sifat beracun dan berpotensi merusak sel-sel dalam tubuh manusia. Limbah ini biasanya berasal dari aktivitas medis, seperti pengobatan kanker atau terapi radiasi.",
extermination: ["Pemisahan dan Penyimpanan: Limbah sitotoksik harus dipisahkan dari limbah lainnya sesuai dengan ketentuan. Gunakan wadah yang sesuai dan aman untuk menyimpannya, seperti wadah yang tahan terhadap bocoran dan tanda pengenal yang jelas.","Perlakuan Pra-Pemusnahan: Sebelum limbah sitotoksik dibuang, ada beberapa metode yang dapat digunakan untuk mengurangi tingkat keberacunan. Misalnya, menggunakan bahan kimia pengikat yang dapat mengikat dan menonaktifkan zat-zat beracun.","Pemusnahan Akhir: Limbah sitotoksik harus dihancurkan atau diinaktifkan sepenuhnya agar tidak lagi berbahaya. Pemusnahan dapat dilakukan melalui berbagai metode seperti pengobatan termal (misalnya, pembakaran dalam incinerator khusus), pengolahan kimiawi, atau proses biologi.","Pengelolaan Limbah Hasil Pemusnahan: Setelah pemusnahan, limbah hasil pemusnahan sitotoksik yang aman harus ditangani dengan benar. Hal ini meliputi pengemasan yang sesuai, tanda pengenal yang jelas, dan pengiriman ke tempat pembuangan akhir yang sesuai dengan peraturan dan regulasi yang berlaku."]},
{name:"Infeksius", description: "Limbah infeksius adalah limbah yang mengandung mikroorganisme patogen atau zat yang berpotensi menyebabkan penyakit. Limbah ini dapat berasal dari rumah sakit, laboratorium medis, atau tempat-tempat lain yang memproduksi atau menggunakan bahan-bahan berbahaya bagi kesehatan manusia.",
extermination: ["Pengolahan termal: Limbah infeksius dapat dihancurkan melalui pengolahan termal, seperti dengan menggunakan incinerator atau mesin sterilisasi berkekuatan tinggi. Suhu tinggi yang diterapkan dalam proses ini dapat membunuh mikroorganisme patogen.","Pengolahan kimia: Beberapa limbah infeksius juga dapat dihancurkan melalui pengolahan kimia menggunakan bahan-bahan seperti klorin atau bahan disinfektan lainnya. Pengolahan kimia ini bertujuan untuk menginaktivasi atau membunuh mikroorganisme patogen yang terdapat dalam limbah.","Autoclaving: Autoclave adalah sebuah alat yang menggunakan kombinasi panas dan tekanan tinggi untuk memusnahkan mikroorganisme dalam limbah infeksius. Proses ini sering digunakan untuk mengolah limbah medis yang padat.","Pengolahan biologi: Beberapa limbah infeksius dapat diolah melalui proses biologi seperti pengomposan atau pengolahan dengan menggunakan mikroorganisme tertentu. Proses ini bertujuan untuk menguraikan atau menghilangkan bahan berbahaya dalam limbah."]
},
{name: "Patologis", description: "Limbah patologis adalah jenis limbah yang berasal dari jaringan tubuh manusia atau hewan yang terinfeksi, organisme patogen, atau sampel laboratorium yang mengandung bahan-bahan biologis berbahaya. Limbah ini sering kali ditemui di rumah sakit, laboratorium medis, atau fasilitas kesehatan lainnya.",
extermination: ["Penanganan Awal: Limbah patologis harus ditangani dengan hati-hati sejak awal untuk menghindari paparan dan penyebaran kontaminan. Gunakan perlengkapan pelindung diri (PPE) yang sesuai, seperti sarung tangan, jas lab, masker, dan pelindung mata.","Pengemasan: Limbah patologis harus ditempatkan dalam wadah yang tahan bocor dan tahan terhadap kerusakan fisik. Gunakan wadah yang telah disetujui dan sesuai dengan peraturan setempat. Wadah tersebut juga harus diberi label yang jelas untuk mengidentifikasi limbah sebagai limbah patologis.","Transportasi: Limbah patologis harus diangkut dengan aman menggunakan kendaraan yang sesuai dan memenuhi peraturan transportasi limbah medis. Pastikan limbah dalam kondisi tertutup dan terkendali selama proses transportasi.","Pemusnahan Akhir: Limbah patologis harus dimusnahkan sepenuhnya untuk mencegah penyebaran penyakit dan kontaminasi lingkungan. Metode pemusnahan yang umum digunakan termasuk pembakaran dalam incinerator khusus yang dapat mencapai suhu tinggi atau perlakuan kimiawi seperti penggunaan bahan disinfektan yang kuat.","Pelaporan dan Dokumentasi: Penting untuk melacak dan mendokumentasikan proses pemusnahan limbah patologis sesuai dengan peraturan yang berlaku. Ini termasuk mencatat tanggal, jenis limbah, metode pemusnahan, dan bukti-bukti lain yang diperlukan."]},
{name: "Farmasi", description: "Limbah farmasi adalah jenis limbah yang berasal dari obat-obatan yang sudah kadaluwarsa, rusak, atau tidak digunakan lagi. Limbah farmasi juga mencakup sisa-sisa obat, bahan kimia berbahaya, atau bahan-bahan farmasi yang tidak lagi diperlukan. Limbah ini biasanya dihasilkan oleh rumah sakit, apotek, laboratorium farmasi, atau fasilitas kesehatan lainnya.",
extermination: ["Identifikasi dan Pemisahan: Identifikasi limbah farmasi yang akan dibuang adalah langkah penting. Pisahkan limbah farmasi dari limbah lainnya, seperti limbah medis atau limbah kimia. Ini memastikan bahwa limbah farmasi ditangani dengan benar dan sesuai dengan persyaratan khusus.","Pengemasan yang Aman: Limbah farmasi harus dikemas dalam wadah yang sesuai dan tahan terhadap bocoran. Gunakan wadah yang telah disetujui dan sesuai dengan peraturan setempat. Pastikan wadah dilengkapi dengan label yang jelas untuk mengidentifikasi limbah farmasi.","Pengumpulan dan Penyimpanan: Tempatkan limbah farmasi dalam area penyimpanan yang aman dan terkendali. Pastikan area penyimpanan terkunci dan hanya diakses oleh personel yang berwenang. Hindari menyimpan limbah farmasi bersama bahan-bahan lain yang tidak sesuai.","Pengangkutan dan Pemusnahan: Limbah farmasi harus diangkut menggunakan kendaraan yang sesuai dan memenuhi peraturan transportasi limbah medis atau farmasi. Pengangkutan harus dilakukan oleh penyedia jasa pengangkutan limbah yang berlisensi. Pemusnahan limbah farmasi dapat dilakukan melalui metode seperti pembakaran dalam incinerator yang sesuai atau melalui proses kimia yang aman.","Pelaporan dan Dokumentasi: Penting untuk mencatat dan mendokumentasikan proses pengangkutan dan pemusnahan limbah farmasi sesuai dengan peraturan yang berlaku. Ini termasuk mencatat tanggal, jenis limbah, metode pemusnahan, dan bukti-bukti lain yang diperlukan."]},
];
module.exports = { wastesType };

